# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20160418_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
    ]
