# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20160418_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendapoint',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
