# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_agendapoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendapoint',
            name='timeEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='agendapoint',
            name='timeStart',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
    ]
