# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_agendapoint_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40, verbose_name='First name')),
                ('secondName', models.CharField(max_length=40, verbose_name='Second name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meeting.Person'),
        ),
    ]
