# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20160418_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meeting.Person'),
        ),
        migrations.AddField(
            model_name='action',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='To be completed by'),
        ),
    ]
