# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_meeting_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='dateTime',
        ),
    ]
