# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_auto_20160504_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='meeting',
            new_name='agendaPoint',
        ),
    ]
