# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_auto_20160504_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='meeting',
            field=modelcluster.fields.ParentalKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='meeting.Meeting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='agendaPoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='meeting.AgendaPoint'),
        ),
    ]
