# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_auto_20160504_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendapoint',
            name='timeEnd',
        ),
        migrations.RemoveField(
            model_name='agendapoint',
            name='timeStart',
        ),
        migrations.AddField(
            model_name='agendapoint',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration'),
        ),
    ]
