# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0015_auto_20160504_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendapoint',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Duration'),
        ),
    ]
